spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/bank
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      fetch_size: 50
      show_sql: true
      format_sql: true
    open-in-view: false

logging:
  level:
    root: INFO
  file:
    name: vital.log
    path: /
